from tangled_up_in_unicode.tangle import Tangle


class Unicode13Data:
    from tangled_up_in_unicode.u13_0_0_data.prop_list_to_property import prop_list_to_property
    from tangled_up_in_unicode.u13_0_0_data.blocks_to_block_start import blocks_to_block_start
    from tangled_up_in_unicode.u13_0_0_data.blocks_to_block_end import blocks_to_block_end
    from tangled_up_in_unicode.u13_0_0_data.property_value_alias_age_short_to_long import property_value_alias_age_short_to_long
    from tangled_up_in_unicode.u13_0_0_data.property_value_alias_bc_short_to_long import property_value_alias_bc_short_to_long
    from tangled_up_in_unicode.u13_0_0_data.property_value_alias_blk_long_to_short import property_value_alias_blk_long_to_short
    from tangled_up_in_unicode.u13_0_0_data.property_value_alias_ccc_short_to_long import property_value_alias_ccc_short_to_long
    from tangled_up_in_unicode.u13_0_0_data.property_value_alias_ea_short_to_long import property_value_alias_ea_short_to_long
    from tangled_up_in_unicode.u13_0_0_data.property_value_alias_gc_short_to_long import property_value_alias_gc_short_to_long
    from tangled_up_in_unicode.u13_0_0_data.property_value_alias_sc_long_to_short import property_value_alias_sc_long_to_short
    from tangled_up_in_unicode.u13_0_0_data.scripts_to_script_start import scripts_to_script_start
    from tangled_up_in_unicode.u13_0_0_data.scripts_to_script_end import scripts_to_script_end
    from tangled_up_in_unicode.u13_0_0_data.east_asian_width_to_east_asian_width_start import east_asian_width_to_east_asian_width_start
    from tangled_up_in_unicode.u13_0_0_data.east_asian_width_to_east_asian_width_end import east_asian_width_to_east_asian_width_end
    from tangled_up_in_unicode.u13_0_0_data.derived_age_to_age_start import derived_age_to_age_start
    from tangled_up_in_unicode.u13_0_0_data.derived_age_to_age_end import derived_age_to_age_end
    from tangled_up_in_unicode.u13_0_0_data.unicode_data_to_name_start import unicode_data_to_name_start
    from tangled_up_in_unicode.u13_0_0_data.unicode_data_to_category_start import unicode_data_to_category_start
    from tangled_up_in_unicode.u13_0_0_data.unicode_data_to_category_end import unicode_data_to_category_end
    from tangled_up_in_unicode.u13_0_0_data.unicode_data_to_bidirectional_start import unicode_data_to_bidirectional_start
    from tangled_up_in_unicode.u13_0_0_data.unicode_data_to_bidirectional_end import unicode_data_to_bidirectional_end
    from tangled_up_in_unicode.u13_0_0_data.unicode_data_to_decimal_start import unicode_data_to_decimal_start
    from tangled_up_in_unicode.u13_0_0_data.unicode_data_to_digit_start import unicode_data_to_digit_start
    from tangled_up_in_unicode.u13_0_0_data.unicode_data_to_numeric_start import unicode_data_to_numeric_start
    from tangled_up_in_unicode.u13_0_0_data.unicode_data_to_combining_start import unicode_data_to_combining_start
    from tangled_up_in_unicode.u13_0_0_data.unicode_data_to_mirrored_start import unicode_data_to_mirrored_start
    from tangled_up_in_unicode.u13_0_0_data.unicode_data_to_mirrored_end import unicode_data_to_mirrored_end
    from tangled_up_in_unicode.u13_0_0_data.unicode_data_to_decomposition_start import unicode_data_to_decomposition_start
    from tangled_up_in_unicode.u13_0_0_data.unicode_data_to_uppercase_start import unicode_data_to_uppercase_start
    from tangled_up_in_unicode.u13_0_0_data.unicode_data_to_lowercase_start import unicode_data_to_lowercase_start
    from tangled_up_in_unicode.u13_0_0_data.unicode_data_to_titlecase_start import unicode_data_to_titlecase_start


tangle = Tangle(
    version="13.0.0",
    data=Unicode13Data,
)
